import { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Soft Blush Shorts",
    price: 1299,
    image: "/images/short1.png",
    category: "Bottoms",
    description: "Soft boutique shorts with a flattering fit and an easy feminine feel.",
  },
  {
    id: 2,
    name: "Twist Front Tube Top",
    price: 999,
    image: "/images/twist-front-tube-top.png",
    category: "Tops",
    description:
      "Twist Front Tube Top\n\n• brand: SHEIN\n• size: xs-small\n• condition: 10/10\n• worn once\n\nMine: 130\n(Grab at your own price 🫰)",
  },
  {
    id: 3,
    name: "Blue Top",
    price: 1499,
    image: "/images/blue-top.png",
    category: "Tops",
    description: "A polished blue top made for feminine everyday outfits.",
  },
  {
    id: 4,
    name: "Self-tie Top",
    price: 1699,
    image: "/images/self-tie-top.png",
    category: "Tops",
    description: "A feminine self-tie top with a soft boutique silhouette.",
  },
  {
    id: 5,
    name: "One Shoulder Rib-Knot Top",
    price: 2199,
    image: "/images/one-shoulder-rib-knot-top.png",
    category: "Tops",
    description: "A one shoulder rib-knot top with a sleek feminine fit.",
  },
  {
    id: 6,
    name: "One Drawstring Ruched Top",
    price: 2399,
    image: "/images/one-drawstring-ruched-top.png",
    category: "Tops",
    description: "A ruched drawstring top with a soft feminine silhouette.",
  },
  {
    id: 7,
    name: "Lace Top",
    price: 1199,
    image: "/images/lace-top.png",
    category: "Tops",
    description: "A delicate lace top with a soft boutique finish.",
  },
  {
    id: 8,
    name: "Fendi Highwaist Shorts",
    price: 1399,
    image: "/images/fendi-highwaist-shorts.png",
    category: "Bottoms",
    description: "Highwaist shorts with a polished boutique-inspired fit.",
  },
  {
    id: 9,
    name: "Lightwash Highwaist Shorts",
    price: 1599,
    image: "/images/lightwash-highwaist-shorts.png",
    category: "Bottoms",
    description: "Lightwash highwaist shorts with an easy everyday fit.",
  },
  {
    id: 10,
    name: "Shoulder Hem Tank Top",
    price: 1299,
    image: "/images/shoulder-hem-tank-top.png",
    category: "Tops",
    description: "A shoulder hem tank top with a clean boutique look.",
  },
];
